### ISSUE TITLE
CCS compatibility 

### ISSUE THREAD

**Issue by Lionward** [CuiMiao-HIT/miniSNV#1]
Thank you for the tool! 

is it possible to  the tool to be run as well on CCS reads? 

best!

**Comment by CuiMiao-HIT** [comment]
Our tool is specifically optimized for ONT data, and while it can perform on CCS data, we cannot assure the same level of effectiveness. 
Best wishes!

**Comment by Lionward** [comment]
Thanks a lot for the fast reply, are you planing to include CCS reads at some point? the new R10 ONT sequencing technologie is pretty similar to CCS reads accuracy and error rate. Would that automatically make the performance similar? 
Best  wishes!

**Comment by CuiMiao-HIT** [comment]
Thank you for the feedback. Incorporating CCS reads is something we're considering for future updates, especially as these technologies converge in performance characteristics. This would likely involve adjustments to enhance compatibility, and we hope to see similar levels of accuracy with ONT's R10. From the perspective of algorithm design, data with high similarity to ONT data can achieve similar performance by using default parameters.
Best wishes!
